# Generated by Django 3.2.12 on 2022-02-19 01:26

from django.db import migrations, models
import django.db.models.deletion
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='게시일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('answer_order', models.IntegerField(verbose_name='답변순서')),
                ('answer_depth', models.IntegerField(default=0, verbose_name='답변깊이')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
            ],
        ),
        migrations.CreateModel(
            name='QnaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20, verbose_name='태그')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='qna/uploads/%Y/%m/%d/')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='qna/uploads/%Y/%m/%d/', verbose_name='첨부파일')),
                ('hit', models.IntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='게시일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('s_or_e_tag', models.CharField(choices=[('S', '스크래치'), ('E', '엔트리'), ('ETC', '기타')], max_length=20, verbose_name='기본 카테고리')),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='QuestionFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(upload_to='qna/file', verbose_name='첨부파일')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_files', to='qna.question')),
            ],
        ),
    ]
