# Generated by Django 4.0.2 on 2022-02-07 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_star',
            field=models.BooleanField(default=False, verbose_name='찜하기'),
        ),
        migrations.AddField(
            model_name='group',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_maker', to=settings.AUTH_USER_MODEL, verbose_name='방장'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupanswer',
            name='parent_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.groupanswer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupanswer',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.grouppost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupanswer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_answer_person', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupanswerreaction',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reacted_group_answer', to='group.grouppost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupanswerreaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_answer_react_person', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grouppost',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='this_group', to='group.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grouppost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_writer_person', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grouppostreaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_react_person', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='초대 코드'),
        ),
        migrations.AlterField(
            model_name='group',
            name='star',
            field=models.IntegerField(default=0, verbose_name='찜하기 개수'),
        ),
    ]
